/**
 * Remark plugin: {%refs TypeName [level]} — port of the v1 markdown-it inline
 * rule (website/markdown/refs.js, Docusaurus 1.14.7).
 *
 * Renders a "References" section: a bulleted index of every type/method that
 * links to the given type, from crossref.json (generated by gencrossref.js).
 * Links are emitted clean (no .html) — relative so they resolve within both
 * current and versioned doc paths.
 */
'use strict';

const fs = require('fs');
const fromMarkdownMod = require('mdast-util-from-markdown');
const fromMarkdown =
  fromMarkdownMod.fromMarkdown || fromMarkdownMod.default || fromMarkdownMod;

const REFS_RE = /^\{%refs\s+([^\s]+)(?:\s+(\d+))?}$/;

module.exports = function remarkRefs(options = {}) {
  const crossrefPath = options.crossref;
  const validBases = options.validBases || null; // version -> Set(id) (D8: refs pointing at docs excluded from a version are dropped)
  let crossref = null;
  return function transformer(tree, file) {
    if (!crossref) {
      crossref = JSON.parse(fs.readFileSync(crossrefPath, 'utf-8'));
    }
    // Determine the version this doc belongs to (for refs filtering).
    // Path example: .../versioned_docs/version-1.0.9/api-bundle.md
    let version = 'current';
    const srcPath = file.path || '';
    const vm = /versioned_docs[\\/]version-([^\\/]+)[\\/]/.exec(srcPath);
    if (vm) version = vm[1];
    const baseSet = validBases && validBases[version];

    const children = tree.children;
    const out = [];
    for (const node of children) {
      if (node.type === 'paragraph' && node.children.length === 1 &&
          node.children[0].type === 'text') {
        const m = REFS_RE.exec(node.children[0].value);
        if (m) {
          const typename = m[1];
          const headlevel = Math.min(6, Number(m[2] || '3'));
          let refs = crossref[typename] || [];
          if (baseSet) {
            // D8: only reference docs that exist in this version
            refs = refs.filter(ref => baseSet.has(ref.base));
          }
          if (refs.length > 0) {
            // Replicate v1 output exactly:
            //   ### References
            //   * [Type](base)
            //     - .[method](base#id)
            out.push(...renderReferences(refs, headlevel));
          }
          continue;
        }
      }
      out.push(node);
    }
    tree.children = out;
  };
};

function renderReferences(refs, headlevel) {
  const mk = '###'.repeat(0) + '#'.repeat(headlevel); // heading of given level
  let md = `${mk} References\n`;
  let prevtype = '';
  let prevmethod = '';
  for (const ref of refs) {
    const { type, method, id, base } = ref;
    if (type !== prevtype) {
      md += `* [${type}](${base})\n`;
    }
    if (method && prevmethod !== method) {
      md += `  - .[${method}](${base}#${id})\n`;
    }
    prevtype = type;
    prevmethod = method;
  }
  const parsed = fromMarkdown(md);
  return parsed.children;
}
